# Generated by Django 5.0.6 on 2025-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_remove_item_owner_lots_comments_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urlimage', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ManyToManyField(to='auctions.category')),
            ],
        ),
    ]
