# Generated by Django 5.0.6 on 2025-02-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_name_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
